#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_65 ]
        then
                cd $OPENSHIFT_DATA_DIR				
                wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.2.2 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget http://mirror.olnevhost.net/pub/apache/maven/binaries/apache-maven-3.2.2-bin.zip 
                unzip apache-maven-3.2.2-bin.zip 
                rm -f apache-maven-3.2.2-bin.zip 
fi

if [ ! -d $OPENSHIFT_DATA_DIR/maven ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir maven
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

cd $OPENSHIFT_REPO_DIR
export MAVEN_USER_HOME=$OPENSHIFT_DATA_DIR/maven
export M2_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.2.2
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_65
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

mvn package -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/maven
